#!/bin/sh
# description: Daemon for quickly looking up Virtualmin servers from procmail
# chkconfig: 2345 99 99

case "$1" in
'start')
	/usr/sbin/virtualmin lookup-domain-daemon
	RETVAL=$?
	if [ "$RETVAL" = "0" ]; then
		touch /var/lock/subsys/lookup-domain
	fi
	;;
'stop')
	kill `cat /var/webmin/lookup-domain-daemon.pid`
	RETVAL=$?
	if [ "$RETVAL" = "0" ]; then
		rm -f /var/lock/subsys/lookup-domain
	fi
	;;
'restart')
	$0 stop ; $0 start
	RETVAL=$?
	;;
*)
	echo "Usage: $0 { start | stop }"
	RETVAL=1
	;;
esac
exit $RETVAL
